name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-06"  # Update this if needed


# compatibility_flags = [ "nodejs_compat" ]

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTVmMDA5NzAtNDQ0YS00NzhlLTlmZWMtYjUyZmY5MmYzODZiIiwidGVuYW50X2lkIjoiZDRlNDZmMjc4MzU5OTZkODU5NjFiNGMyMTE3NDA2MTY5YzlkZDhmZDU5MmQxZmYxMDg2YzBjYmMzOGYyOTE2YiIsImludGVybmFsX3NlY3JldCI6IjcyZWQ0ZWU0LTRlYmQtNDMwMi04ZGI3LWU1NjA3M2U2NWM2ZSJ9.IEM9M8pJ1I-DdgPZCoh7xBvbWLjnIvl0DvzR2LxoIDQ"
JWT_SECRET="aaahghje"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1